"""Generate the level 200..MAX_LEVEL-1 EXP table shared by kaentake and Cosmic.

The client (src/exptable.h) and the server (constants/game/ExpTable.java) must hold identical
values, or the EXP bar and percentages disagree with what the server levels you on. Always
regenerate both from this script instead of editing either array by hand.

Curve: exp[200] is the vanilla value already in Cosmic's table. Up to level 300 each level costs
x1.0548 the previous one (the exact ratio the vanilla table uses from ~150 to 199); from 301 the
ratio falls linearly to x1.02 at the last level so EXP stays well inside int64.

    python tools/gen_exptable.py            # writes src/exptable.h, prints the Java array
"""
import pathlib

MAX_LEVEL = 500
BASE_LEVEL = 200
BASE_EXP = 1697021059  # Cosmic ExpTable exp[200]
RATIO_VANILLA = 1.0548
RATIO_END = 1.02
SOFTEN_FROM = 300


def ratio(level):
    if level <= SOFTEN_FROM:
        return RATIO_VANILLA
    t = (level - SOFTEN_FROM) / (MAX_LEVEL - 1 - SOFTEN_FROM)
    return RATIO_VANILLA - (RATIO_VANILLA - RATIO_END) * t


def table():
    values = [BASE_EXP]
    for level in range(BASE_LEVEL + 1, MAX_LEVEL):
        values.append(int(values[-1] * ratio(level) + 0.5))
    assert sum(values) < 2**63
    return values


def chunks(values, n=6):
    for i in range(0, len(values), n):
        yield values[i:i + n]


def main():
    values = table()
    root = pathlib.Path(__file__).resolve().parent.parent

    lines = [
        "#pragma once",
        "// Generated by tools/gen_exptable.py - do not edit by hand.",
        "// Must match Server/src/main/java/constants/game/ExpTable.java (expPost200).",
        "",
        f"constexpr int kExpTableBase = {BASE_LEVEL};",
        f"constexpr int kMaxLevel = {MAX_LEVEL};",
        "",
        f"constexpr long long kExpTable[{len(values)}] = {{",
    ]
    for row in chunks(values):
        lines.append("    " + ", ".join(f"{v}LL" for v in row) + ",")
    lines.append("};")
    (root / "src" / "exptable.h").write_text("\n".join(lines) + "\n", encoding="ascii")

    print(f"// levels {BASE_LEVEL}..{MAX_LEVEL - 1}, generated by kaentake/tools/gen_exptable.py")
    print(f"private static final long[] expPost200 = {{")
    for row in chunks(values):
        print("        " + ", ".join(f"{v}L" for v in row) + ",")
    print("};")


if __name__ == "__main__":
    main()
