# Build injector
add_library(injector SHARED
    injector.cpp
    system.cpp
    bypass.cpp
    inlink.cpp
    resman.cpp
    avatar.cpp
    itemeff.cpp
    resolution.cpp
    mobhptag.cpp
    tooltip.cpp
    itemicon.cpp
    tempstat.cpp
    shadowpartner.cpp
    maxlevel.cpp
    maxhpmp.cpp
    maxmeso.cpp
    clientsocket.cpp
    worldmapdata.cpp
    worldmapinfo.cpp
    hyperteleportrock.cpp
    uiDamageRank.cpp
    damagerankinput.cpp
    damageskin.cpp
    damageskinpicker.cpp
    coloringprism.cpp
    weapontint.cpp
    cashshopwnd.cpp
    storagebag.cpp
    inventorynx.cpp
    skillui.cpp
    longkeyboard.cpp
    quickslotdlg.cpp
    magicdmg.cpp
    critrouting.cpp
    critratedisplay.cpp
    statdetaillayout.cpp
    statuilayout.cpp
    monsterbook.cpp
    monsterbookfoundin.cpp
    monsterbookdrops.cpp
    monsterbooksearch.cpp
    crashlog.cpp
    stringpool.cpp
    debug.cpp
    hook.cpp
)

target_precompile_headers(injector PRIVATE pch.h)

target_link_libraries(injector PRIVATE
    Detours
    WzLib
)

set_target_properties(injector PROPERTIES
    OUTPUT_NAME ${PROJECT_NAME}
)

add_custom_command(TARGET injector POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_CURRENT_SOURCE_DIR}/Custom.wz"
        "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}"
)


# Build launcher
add_executable(launcher WIN32
    launcher.manifest
    launcher.rc
    launcher.cpp
    debug.cpp
)

target_link_options(launcher PRIVATE "/MANIFEST:NO")

target_link_libraries(launcher PRIVATE
    Detours
)

set_target_properties(launcher PROPERTIES
    OUTPUT_NAME ${PROJECT_NAME}
)